### ISSUE TITLE
タイピングゲームの時に正解しているのに次に進まないエラー

### ISSUE THREAD

**Issue by Masahiro-QUEST** [Masahiro-QUEST/typingGame#7]
### コンソールのログ
-bundler.js:40  [Vue warn]: Unhandled error during execution of render function 
  at <CurrentQuestionComponent currentQuestionImage="NorwegianForestCat.jpg" currentQuestionEnglish="Norwegian Forest Cat" currentQuestionJapanese="ノルウェージャンフォレストキャット"  ... > 
  at <NyanStage onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {gameStart: ƒ, restartGame: ƒ, getRandomQuestion: ƒ, setEndTime: ƒ, createUser: ƒ, …} > > 
  at <RouterView> 
  at <App>
warn @ runtime-core.esm-bundler.js:40
logError @ runtime-core.esm-bundler.js:230
handleError @ runtime-core.esm-bundler.js:222
renderComponentRoot @ runtime-core.esm-bundler.js:943
componentUpdateFn @ runtime-core.esm-bundler.js:5720
run @ reactivity.esm-bundler.js:190
instance.update @ runtime-core.esm-bundler.js:5763
updateComponent @ runtime-core.esm-bundler.js:5588
processComponent @ runtime-core.esm-bundler.js:5521
patch @ runtime-core.esm-bundler.js:5119
patchBlockChildren @ runtime-core.esm-bundler.js:5424
patchElement @ runtime-core.esm-bundler.js:5332
processElement @ runtime-core.esm-bundler.js:5199
patch @ runtime-core.esm-bundler.js:5116
patchBlockChildren @ runtime-core.esm-bundler.js:5424
patchElement @ runtime-core.esm-bundler.js:5332
processElement @ runtime-core.esm-bundler.js:5199
patch @ runtime-core.esm-bundler.js:5116
componentUpdateFn @ runtime-core.esm-bundler.js:5729
run @ reactivity.esm-bundler.js:190
instance.update @ runtime-core.esm-bundler.js:5763
callWithErrorHandling @ runtime-core.esm-bundler.js:173
flushJobs @ runtime-core.esm-bundler.js:406
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:298
queueJob @ runtime-core.esm-bundler.js:292
scheduler @ runtime-core.esm-bundler.js:1845
triggerEffect @ reactivity.esm-bundler.js:400
triggerEffects @ reactivity.esm-bundler.js:390
trigger @ reactivity.esm-bundler.js:358
set @ reactivity.esm-bundler.js:543
$data.startFlg.$data.current_question_counts.$data.question_count.onUpdate:modelValue._cache.<computed>._cache.<computed> @ GamePage.vue:31
callWithErrorHandling @ runtime-core.esm-bundler.js:173
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:182
emit @ runtime-core.esm-bundler.js:730
onInput._cache.<computed>._cache.<computed> @ TypeFormComponent.vue:9
callWithErrorHandling @ runtime-core.esm-bundler.js:173
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:182
invoker @ runtime-dom.esm-bundler.js:345
runtime-core.esm-bundler.js:40  [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <CurrentQuestionComponent currentQuestionImage="NorwegianForestCat.jpg" currentQuestionEnglish="Norwegian Forest Cat" currentQuestionJapanese="ノルウェージャンフォレストキャット"  ... > 
  at <NyanStage onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {gameStart: ƒ, restartGame: ƒ, getRandomQuestion: ƒ, setEndTime: ƒ, createUser: ƒ, …} > > 
  at <RouterView> 
  at <App>
warn @ runtime-core.esm-bundler.js:40
logError @ runtime-core.esm-bundler.js:230
handleError @ runtime-core.esm-bundler.js:222
callWithErrorHandling @ runtime-core.esm-bundler.js:176
flushJobs @ runtime-core.esm-bundler.js:406
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:298
queueJob @ runtime-core.esm-bundler.js:292
scheduler @ runtime-core.esm-bundler.js:1845
triggerEffect @ reactivity.esm-bundler.js:400
triggerEffects @ reactivity.esm-bundler.js:390
trigger @ reactivity.esm-bundler.js:358
set @ reactivity.esm-bundler.js:543
$data.startFlg.$data.current_question_counts.$data.question_count.onUpdate:modelValue._cache.<computed>._cache.<computed> @ GamePage.vue:31
callWithErrorHandling @ runtime-core.esm-bundler.js:173
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:182
emit @ runtime-core.esm-bundler.js:730
onInput._cache.<computed>._cache.<computed> @ TypeFormComponent.vue:9
callWithErrorHandling @ runtime-core.esm-bundler.js:173
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:182
invoker @ runtime-dom.esm-bundler.js:345
app.js:1388  Uncaught (in promise) Error: Cannot find module './NorwegianForestCat.jpg'
    at webpackContextResolve (app.js:1388:11)
    at webpackContext (app.js:1383:11)
    at Proxy.render (CurrentQuestionComponent.vue:4:1)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5720:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:1)
    at instance.update (runtime-core.esm-bundler.js:5763:1)
    at updateComponent (runtime-core.esm-bundler.js:5588:1)
    at processComponent (runtime-core.esm-bundler.js:5521:1)
    at patch (runtime-core.esm-bundler.js:5119:1)
webpackContextResolve @ app.js:

**Comment by Masahiro-QUEST** [comment]
このエラーの出力から、NorwegianForestCat.jpgという名前の画像ファイルが見つからないという問題が発生しているようです。これはVue.jsのコンポーネントで画像を表示しようとしている際に、指定されたパスに該当の画像ファイルが存在しないために起こっています。

以下の解決策を試してみてください。

画像ファイルの存在確認: NorwegianForestCat.jpgという名前の画像ファイルがプロジェクト内に存在しているか確認してみてください。プロジェクトのディレクトリ内でファイルが見つからない場合、エラーが発生します。

ファイルパスの確認: NorwegianForestCat.jpgへのパスが正しく設定されているか確認してみてください。相対パスや絶対パスが間違っていると、ファイルを見つけられずにエラーが発生します。

ケースセンシティビティ: ファイル名やディレクトリ名が大文字・小文字を正しく扱っているか確認してみてください。一部のファイルシステムでは大文字と小文字を区別しますので、NorwegianForestCat.jpgとnorwegianforestcat.jpgは異なるファイルとして扱われます。

画像ファイルのインポート: NorwegianForestCat.jpgを直接インポートして使用してみてください。以下のように記述できます:
